### GET ALL CHATS (TOKEN REQUIRED)
GET http://localhost:1234/chats

### GET BY ID (TOKEN REQUIRED)
GET http://localhost:1234/chats/3

### GET ALL MEMBERS (TOKEN REQUIRED)
GET http://localhost:1234/chats/1/members

### ADD MEMBERS (TOKEN REQUIRED)
POST http://localhost:1234/chats/1/members
Content-Type: application/json

{
    "miembro": "b126ee51-2e39-11ef-8238-50ebf6283cbf"
}

### KICK MEMBER TO CHAT (TOKEN REQUIRED)
DELETE http://localhost:1234/chats/1/members/b126ee51-2e39-11ef-8238-50ebf6283cbf

### CREATE (TOKEN REQUIRED)
POST http://localhost:1234/chats
Content-Type: application/json

{
    "nombre": "Yorich"
}

### UPDATE (TOKEN REQUIRED)
PATCH http://localhost:1234/chats/6
Content-Type: application/json

{
    "nombre": "Yorich 1"
}

### DELETE (TOKEN REQUIRED)
DELETE http://localhost:1234/chats/6

### GET MESSAGES BY CHAT (TOKEN REQUIRED)
GET http://localhost:1234/chats/1/messages


### CREATE MESSAGE (TOKEN REQUIRED)
POST http://localhost:1234/chats/1/messages
Content-Type: application/json

{
    "uuid_usuario": "b126cb40-2e39-11ef-8238-50ebf6283cbf",
    "contenido": "Que bien uwu"
}
