### GET ALL (TOKEN REQUIRED)
GET http://localhost:1234/publications

### GET BY ID (TOKEN REQUIRED)
GET http://localhost:1234/publications/1

### CREATE (TOKEN REQUIRED)
POST http://localhost:1234/publications
Content-Type: application/json

{
    "uuid_usuario": "169d772e-2ecb-11ef-95a9-50ebf6283cbf",
    "contenido": "Hola estoy exponiendo xd"
}

### UPDATE (TOKEN REQUIRED)
PATCH http://localhost:1234/publications/14
Content-Type: application/json

{
    "contenido": "Hola :("
}

### DELETE (TOKEN AND ROLE REQUIRED)
DELETE http://localhost:1234/publications/14

