### GET ALL (NO TOKEN OR ROLE REQUIRED)
GET http://localhost:1234/users

### GET BY ID (TOKEN AND ROLE REQUIRED)
GET http://localhost:1234/users/b126cb40-2e39-11ef-8238-50ebf6283cbf

### GET ALL CHATS BY USER
GET http://localhost:1234/users/b126cb40-2e39-11ef-8238-50ebf6283cbf/chats

### CREATE / USER (TOKEN REQUIRED, NO ROLE REQUIRED)
POST http://localhost:1234/users
Content-Type: application/json

{
    "username": "23Lamse",
    "role": 1,
    "nombre": "Yorich Sorem",
    "apellidopaterno": "Lamse",
    "apellidomaterno": "Kalth",
    "email": "yoLamse@gmail.com",
    "contraseña": "12345",
    "rutaAvatar": "http://avatars/yoLamse.jpg"
}


### CREATE / ADMIN (TOKEN REQUIRED, NO ROLE REQUIRED)
POST http://localhost:1234/users
Content-Type: application/json

{
    "username": "24Jhon",
    "role": 2,
    "nombre": "Jonh Yalak",
    "apellidopaterno": "Lamse",
    "apellidomaterno": "Rito",
    "email": "yoJohn@gmail.com",
    "contraseña": "1234ABCD",
    "rutaAvatar": "http://avatars/yoRITO.jpg"
}


### UPDATE (TOKEN REQUIRED, NO ROLE REQUIRED)
PATCH http://localhost:1234/users/b126cb40-2e39-11ef-8238-50ebf6283cbf
Content-Type: application/json

{
    "email": "youLamse@gmail.com"
}


### DELETE (TOKEN REQUIRED, NO ROLE REQUIRED)
DELETE http://localhost:1234/users/b126cb40-2e39-11ef-8238-50ebf6283cbf