### Obtener todos los alumnos
GET http://localhost:1234/users

### Obtener alumno por ID
GET http://localhost:1234/users/1

### Creando un alumno
POST http://localhost:1234/users

### Actualizando un alumno:
PATCH http://localhost:1234/users/1