### Obtener todos los usuarios
GET http://localhost:1234/users

### Obtener usuario por ID
GET http://localhost:1234/users/b126cb40-2e39-11ef-8238-50ebf6283cbf

### Crear un usuario
POST http://localhost:1234/users
Content-Type: application/json

{
    "alias": "ola123",
    "nombre": "Luis Bryan",
    "apellido": "Cabello Ortiz",
    "email": "dfsdf@gmail.com",
    "contraseña": "sdfsdf",
    "rutaAvatar": "http://avatars/arroz.jpg"
}

### Actualizar un usuario
PATCH http://localhost:1234/users/d98aa2ac-2f6c-11ef-86cf-50ebf6283cbf
Content-Type: application/json

{
    "email": "ola12345@gmail.com"
}

### Borrar usuario de forma lógica
DELETE http://localhost:1234/users/d98aa2ac-2f6c-11ef-86cf-50ebf6283cbf



###############################################################################
### PUBLICACIONES

### Listar todas las publicaciones
GET http://localhost:1234/publications

### Obtener publicación por ID
GET http://localhost:1234/publications/14

### Crear una publicación
POST http://localhost:1234/publications
Content-Type: application/json

{
    "uuid_usuario": "169d772e-2ecb-11ef-95a9-50ebf6283cbf",
    "contenido": "Hola estoy exponiendo xd"
}

### Actualizar una publicación
PATCH http://localhost:1234/publications/14
Content-Type: application/json

{
    "contenido": "Hola :("
}


### Borrar una publicación
DELETE http://localhost:1234/publications/14





###############################################################################
### COMENTARIOS AYUDA

### Listar los comentarios de una publicacion
GET http://localhost:1234/publications/2/comments


### Crear un comentario
POST http://localhost:1234/publications/2/comments
Content-Type: application/json

{
    "uuid_usuario": "b126cb40-2e39-11ef-8238-50ebf6283cbf",
    "contenido": "Que bien uwu"
}

### Actualizar un comentario
PATCH http://localhost:1234/publications/1/comments/11
Content-Type: application/json

{
    "contenido": "Holaaaaaa"
}

### Borrar un comentario
DELETE http://localhost:1234/publications/1/comments/11


#############################################################
### REACCIONES

### Obtener todas las reacciones de una publicación
GET http://localhost:1234/publications/1/reactions

### Obtener reaccion por publicacion y tipo
GET http://localhost:1234/publications/12/reactions/1

### Añadir una nueva reaccion
POST http://localhost:1234/publications/1/reactions
Content-Type: application/json

{
    "user_uuid": "b126eb5b-2e39-11ef-8238-50ebf6283cbf",
    "reaction_id": 5
}